apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://argoproj.github.io/argo-helm
    path: chart
    helm:
      valueFiles:
      - $configs/helm/argocd/values.yaml
      releaseName: argocd
    chart: argo-cd
    targetRevision: 9.5.9
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
