apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://charts.external-secrets.io
    path: chart
    helm:
      valueFiles:
      - $configs/helm/external-secrets-operator/values.yaml
      releaseName: external-secrets-operator
    chart: external-secrets
    targetRevision: 2.4.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets-operator
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
