apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://kubernetes-sigs.github.io/headlamp/
    path: chart
    helm:
      valueFiles:
      - $configs/helm/headlamp/values.yaml
      releaseName: headlamp
    chart: headlamp
    targetRevision: 0.41.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
