apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://prometheus-community.github.io/helm-charts
    path: chart
    helm:
      valueFiles:
      - $configs/helm/prometheus/values.yaml
      releaseName: prometheus
    chart: kube-prometheus-stack
    targetRevision: 84.5.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
