apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://helm.releases.hashicorp.com
    path: chart
    helm:
      valueFiles:
      - $configs/helm/vault/values.yaml
      releaseName: vault
    chart: vault
    targetRevision: 0.32.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
