clientInfoSecret:
    #ENC[AES256_GCM,data:Khqb0moAzLUieoA+I+cInOcWykopcuASHOTck1S59UdjrWgthaLb5A3TRnwG,iv:7dYnR2LMza41ZDD5/TfUxafgm7lyO7g4p5pRm18i1AE=,tag:HHDNbTELu/oiDr4rvUUQJQ==,type:comment]
    clients:
        #ENC[AES256_GCM,data:GRZPQQXFJZzt4xezwbFOYe9f2u5m1iwXc1qDyDNq6QZl8g==,iv:Mg+k9fC9T7nWbt++gnt00KC/N2zNkTG0PbOGZRCiP+k=,tag:dwZQ8gfXcBt5c3zazneoKg==,type:comment]
        - host: ENC[AES256_GCM,data:1qM3VSE8jupFJhX5/Q==,iv:Hq2ABkRYFvhvqf4RhdBDElY8XhoyQcJMxh2mymWrsTc=,tag:rh3vN5YOOoPlF2MFS4LwRA==,type:str]
          #ENC[AES256_GCM,data:+z9YlKhUmnXOJntarwVP1SBHmfZ5xD2JHejt/C+iGreb2bsh+7I=,iv:KzIvEDr9a6crbjg0LUGGTG1dovNQspwzYG08i17P+eU=,tag:qaKQMSrOFtkq1ZbgwEhaAg==,type:comment]
          https: ENC[AES256_GCM,data:h9xpfGk=,iv:Jr4+HrnGOEIwOCC7THaJXtPAux6LJWCwMKVQS1PKFtg=,tag:zBNIz4CyRZywsH0qD/navg==,type:bool]
          #ENC[AES256_GCM,data:FSKrzwdmxcXzwbQltk48gIANZ/PwimN40oEC4NJip/FTliJDrMqe,iv:T2U6iojVXlwday3swBLsdPkrzJBKE59LsBITJsTYmWk=,tag:uhdljniwF1OOnKWQa3/CaA==,type:comment]
          password: ENC[AES256_GCM,data:utXEJiZkoXM=,iv:3c8dUUKPb/FXY/CP+0nOJvpnHHx/qbbdLxaO7rDwPtw=,tag:XNl6J4hL3TnLrN3GJm/GhA==,type:str]
          #ENC[AES256_GCM,data:uGs7Ru5jRUboP5c0romq+FwS/7iOI8NM8xijW/VmRHe9V8a5+ofFiVPw8E2rse4j4w7a+9dfMTjSt7LNHWR+,iv:r4xZi6efRMprDdNRKup5BXC8xWccug79vLczZLi8T0k=,tag:ykZ+WeiGwGq32UBLqSpzTA==,type:comment]
          port: ENC[AES256_GCM,data:NWdVmA==,iv:6dTFoVvwjtki7fY+e55IzXBOwQd/sClBEoOAU8bmr7s=,tag:zruoeFPxJICfiXvK62tiFQ==,type:int]
          #ENC[AES256_GCM,data:FfYUXR1V4YrCbVnXV2fUTs9K7yxq8sD5Nf8SROzzAbKDT7k=,iv:XR1dQyLU8wteq1XPNOufCnJu2AaR0hZWY+t76p0iK4s=,tag:JyOBWf3No7vF8QuU44592w==,type:comment]
          username: ENC[AES256_GCM,data:e6BVxbbJoNw=,iv:Whka9X3/cNCJM50RTG26FM6JUMIIT+60c4TaHP2TvXk=,tag:dgvzWEnCRPnGkbLUPIBhvg==,type:str]
        - host: ENC[AES256_GCM,data:cAy4Uf0SljBUass3yg==,iv:Ka+32FgMdR8yIXIC+8XdUCpgk2G6bfQntPDBdCbqQNs=,tag:e/pJAfEOiVhLrcKbBGMzyw==,type:str]
          https: ENC[AES256_GCM,data:6zwgVg==,iv:hlQBEU/dZCZ0JCL2IXvbUiKB1P8j0UOZKo9N7IANyc8=,tag:K2td7Q7OWHx8eD2vzghYOg==,type:bool]
          password: ENC[AES256_GCM,data:JtHlZkqmX/M=,iv:3XP8mhZI8qQvUk1leRDyNZktI8VmedzG+pghg8sWtf4=,tag:cfmrMkkwPKAgGYZSwJuOdA==,type:str]
          port: ENC[AES256_GCM,data:ms0cKQ==,iv:4oPkxsIpPblaagRBQzgeOtygJZoG+APljZis5rx7FPQ=,tag:kSGWsgh8BzSvOfrm0A9wkw==,type:int]
          username: ENC[AES256_GCM,data:XYM5HzdFWSE=,iv:iSC/YWPibv0Zym3o45X1ohXStLfDB3VHEpzwyygS0Wk=,tag:hZZudzvR4mO456Or0c6Piw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-01T03:52:34Z"
    mac: ENC[AES256_GCM,data:gvDEmSQFyvWn0lMmynBC2uT6UBKGvuYMUAUFNIjoa8PC9/78gqMAz3Ud6GzmmCiNaZBxk38p9jByqcQvgU0vTbkPY0xU7CWtJBaeEyvumQGooVCkxDaFxITeV5zfvky8bOfVc1fmwsGHlqOQI6Znu7qybHKHaKDC6M0Qc4Z83y8=,iv:1oIlq9jU5mD6ydp/LDQcTDgIA2DB596cVzQfQtkBNGw=,tag:slBFurc80IxBLP+ZXpDkxw==,type:str]
    pgp:
        - created_at: "2024-01-01T03:52:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3XPPdnSyaVDAQv/UNN6FbiUnasQZljR//Soyxkhmkf/RaKBqUdx4h4P+Eb0
            6Y+HxAQgxa/BTfROvmZAQ2JyepPtUwLL6DMWeB1OXsoShXpC1DIS5kJtw15nzPMF
            +J4OhJ22VqYda1AHBIOESJf1Tk0qyvujuJecKw2/O1a2hx606DJ0qe4csoD3zss0
            eiV1c3H5VyGPB+UgLF8FpynWSTSU8V0k/pZ2kdEp914qAx0ZiO4qG7RJWhy6wrNB
            h7OgxxJ2zaH6Oo72Hz9jJxB6mlSva/SdzSknxT3QMcR28SvWZ09KYoBTTwtTHhqH
            2Yw+jAw5rt+lVcjvhliiROxGH4FAffnmtvS1nr5qlRVfWU41KGTTrsne9uBZ6UEv
            v75IEmvO8fx7FuXPtxroPSegWd7m8wMXc77Y2WfHx4O6MRfvChJ+XUeCxB1ntnt5
            zcVkkfsjbA/ReGYbWet3/9tqJK7YOl/zsejc+Ws96DViPSXSEZXSroeDr2Jed64v
            AQ0HYRDHG28ZXkikS5rt0l4BI1nah7xG2hX9Q8AY+seuxZNcnVObZAF1JytDWyjT
            wXQDARJ48LD8okl50xsGAqOoygK2Ld2sEXSLH6oCwL2qvT8elZihUTNainp0RvCo
            /4esJFoCW0md02VS53f/
            =e9IG
            -----END PGP MESSAGE-----
          fp: F33DE00227B9665679FCE59756D034A73215C8E2
    unencrypted_suffix: _unencrypted
    version: 3.8.1
