cluster:
  name: kubernetes
k8sServiceHost: k8sapiserver.cluster.orenet.net
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 2
routingMode: tunnel
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnelProtocol: vxlan
bpf:
  masquerade: true

