apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-coredns
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://coredns.github.io/helm
    path: chart
    helm:
      valueFiles:
      - $configs/helm/external-dns-coredns/values.yaml
      releaseName: coredns
    chart: coredns
    targetRevision: 1.45.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
