apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://gitlab.cluster.orenet.net/y-sera/homecluster.git
    ref: configs
    targetRevision: HEAD
  - repoURL: https://kubernetes-sigs.github.io/external-dns/
    path: chart
    helm:
      valueFiles:
      - $configs/helm/external-dns/values.yaml
      releaseName: external-dns
    chart: external-dns
    targetRevision: 1.21.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
