apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  commonName: cluster.orenet.net
  dnsNames:
  - alertmanager.cluster.orenet.net
  - cluster.orenet.net
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: alertmanager 
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: alertmanager-cert
  subject:
    organizations:
    - orenet
  usages:
  - digital signature
