apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  commonName: cluster.orenet.net
  dnsNames:
  - minio-operator.cluster.orenet.net
  - cluster.orenet.net
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: minio-operator
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: minio-operator-cert
  subject:
    organizations:
    - orenet
  usages:
  - digital signature
