{{- $cn := .Values.cert.commonName }}
{{- $dns := list $cn }}
{{- $ca_duration_days := .Values.cert.caDurationDays | int }}
{{- $ca := genCA .Values.cert.caName $ca_duration_days }}

{{- $client_cn := .Values.cert.client.commonName }}
{{- $client_duration_days := .Values.cert.client.durationDays | int }}
{{- $client_cert := genSignedCert $client_cn nil $dns $client_duration_days $ca }}

{{- $server_cn := .Values.cert.server.commonName }}
{{- $server_duration_days := .Values.cert.server.durationDays | int }}
{{- $server_cert := genSignedCert $server_cn nil $dns $server_duration_days $ca }}

{{- $peer_cn := .Values.cert.peer.commonName }}
{{- $peer_duration_days:= .Values.cert.peer.durationDays | int }}
{{- $peer_cert := genSignedCert $peer_cn nil $dns $peer_duration_days $ca }}
---
{{- if .Values.cert.client.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cert.client.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $client_cert.Cert | b64enc }}
  tls.key: {{ $client_cert.Key | b64enc }}
{{- end }}
---
{{- if .Values.cert.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cert.server.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $server_cert.Cert | b64enc }}
  tls.key: {{ $server_cert.Key | b64enc }}
{{- end }}
---
{{- if .Values.cert.peer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cert.peer.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $peer_cert.Cert | b64enc }}
  tls.key: {{ $peer_cert.Key | b64enc }}
{{- end -}}
