apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "apiserver"
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.1.2/32"
  serviceSelector:
    matchLabels:
      lbpool: apiserver
