apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "external-dns"
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.2.64/32"
  serviceSelector:
    matchLabels:
      lbpool: external-dns
