apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingress"
  namespace: kube-system
spec:
  blocks:
  - start: "192.168.1.3"
    stop: "192.168.1.15"
  serviceSelector:
    matchLabels:
      lbpool: ingress 
