apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "any-pool"
  namespace: kube-system
spec:
  blocks:
  - start: "192.168.2.4"
    stop: "192.168.2.31"
  serviceSelector:
    matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
         - {key: lbpool, operator: DoesNotExist}
