apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingress"
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.2.3/32"
  serviceSelector:
    matchLabels:
      lbpool: ingress
